(()=>{'use strict';
const D=window.HEXA_DATA,E=window.HexaEngine,$=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString('en-US'),escape=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const paths={hex:'M12 2 21 7v10l-9 5-9-5V7Z M12 2v20 M3 7l18 10 M21 7 3 17',search:'m20 20-5-5 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',chevron:'m7 10 5 5 5-5',info:'M12 11v6 M12 7h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',menu:'M4 6h16 M4 12h16 M4 18h16',download:'M12 3v12 m-5-5 5 5 5-5 M4 16v5h16v-5',upload:'M12 16V4 m-5 5 5-5 5 5 M4 16v5h16v-5',sliders:'M4 5h16 M4 12h16 M4 19h16 M8 2v6 M16 9v6 M10 16v6',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12 M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',calendar:'M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2Z M7 3v5 M17 3v5 M3 11h18 M7 15h3 M14 15h3',reset:'M3 10a9 9 0 1 1 1 8 M3 4v6h6',check:'m5 12 4 4L19 6','arrow-right':'M4 12h16 m-6-6 6 6-6 6',external:'M14 3h7v7 M21 3 10 14 M10 3H3v18h18v-7',close:'m6 6 12 12 M18 6 6 18',star:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',undo:'M3 10h11a7 7 0 0 1 7 7v3 M3 10l6-6 M3 10l6 6',lock:'M6 10h12v11H6Z M8 10V6a4 4 0 0 1 8 0v4'};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.hex}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let saved={};try{saved=JSON.parse(localStorage.getItem('hexa-planner-v1')||'{}');if(!saved||typeof saved!=='object')saved={};}catch{}
let selected=D.classes.find(c=>c.id===saved.selected)?.id||'night_lord',mode='progress',filter='All',query='',category='All classes',drafts=saved.drafts&&typeof saved.drafts==='object'?saved.drafts:{},history=[],toastTimer;
let settings=E.settings(saved.settings),matrixSelected=null;
const current=()=>D.classes.find(c=>c.id===selected);
const profile=()=>mode==='preview'?E.defaults(current()):E.clean(current(),drafts[selected]);
const isPreview=()=>mode==='preview';
function save(){try{localStorage.setItem('hexa-planner-v1',JSON.stringify({selected,drafts,settings}));$('saved-status').innerHTML='<span class="status-dot"></span>Saved on this device';}catch{$('saved-status').textContent='Storage unavailable · changes will not be saved';}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3600);}
function capture(){history.push({classId:selected,profile:JSON.parse(JSON.stringify(profile()))});if(history.length>30)history.shift();}
const levelField=el=>el?.matches?.('input[data-level],input[data-goal],input[data-janus],input[data-material]');
let restoringLevelFocus=false;
function update(p){
 const editing=levelField(document.activeElement)?document.activeElement:null;
 const start=editing?.selectionStart,end=editing?.selectionEnd;
 drafts[selected]=E.clean(current(),p);save();renderPlanner();renderLibrary();
 if(editing){const replacement=$(editing.id);if(replacement){editing.min=replacement.min;editing.max=replacement.max;replacement.replaceWith(editing);restoringLevelFocus=true;editing.focus({preventScroll:true});editing.setSelectionRange(start,end);restoringLevelFocus=false;}}
}
function coreFor(id){return current().cores.find(c=>c.id===id);}
function skillIcon(core,large=false){return `<button type="button" data-describe="${core.id}" data-description-open="${core.id}" aria-label="${escape(core.name)} skill description" class="skill-icon${large?' large':''}" data-fallback="${escape(core.short)}"><img src="${core.icon}" alt="" loading="lazy" width="32" height="32"></button>`;}
function imageFallbacks(){document.querySelectorAll('img').forEach(img=>{img.onerror=()=>{img.parentElement?.classList.add('image-failed');img.style.visibility='hidden';};});}
function renderLibrary(){const list=D.classes.filter(c=>(!query||`${c.name} ${c.ko}`.toLowerCase().includes(query.toLowerCase()))&&(category==='All classes'||c.category===category));$('class-count').textContent=query||category!=='All classes'?`${list.length} found`:`${D.available} / ${D.total}`;$('class-list').innerHTML=list.length?list.map(c=>`<button class="class-item class-image-tile ${c.id===selected?'selected':''}" data-class="${c.id}" aria-label="${escape(c.name)}" title="${escape(c.name)}" aria-current="${c.id===selected?'true':'false'}"><img src="assets/classes/${c.id}.png" alt="${escape(c.name)}" width="152" height="74" loading="lazy">${c.id===selected?`<span class="selected-check">${icon('check')}</span>`:''}</button>`).join(''):'<div class="library-empty">No classes found.<br>Try another name or category.</div>';}
function chooseClass(id){if(!D.classes.some(c=>c.id===id))return;selected=id;filter='All';history=[];matrixSelected=null;save();renderLibrary();renderPlanner();closeLibrary();}
function renderPlanner(){window.HexaSkillDetails.hide();const c=current(),p=profile();$('class-name').textContent=c.name;$('class-category').textContent=c.category.toUpperCase()+' / '+c.ko;$('class-emblem').innerHTML=c.cores.length?`<img src="${(c.cores.find(x=>x.id==='skillCore1')||c.cores[0]).icon}" alt="">`:`<span>${escape(c.name.slice(0,2))}</span>`;$('progress-mode').setAttribute('aria-pressed',String(!isPreview()));$('preview-mode').setAttribute('aria-pressed',String(isPreview()));$('planner').hidden=!c.available;$('unavailable').hidden=c.available;
 if(!c.available){$('unavailable').innerHTML=`${icon('lock')}<h3>No order available for ${escape(c.name)}</h3><p>This snapshot does not contain a usable order for this class. Your other class plans are still saved.</p><button class="primary-button" data-action="choose-available">Explore supported classes ${icon('arrow-right')}</button>`;return;}
 document.querySelectorAll('[data-order-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.orderMode===settings.orderMode)));const hasThird=c.cores.some(core=>core.id==='skillCore3');$('include-third').disabled=!hasThird;$('include-third').checked=hasThird&&settings.includeThirdSkill;$('third-skill-hint').textContent=hasThird?'Off by default for your GMS setup':'Not present in this class’s source order';$('order-note').textContent=(settings.orderMode==='erda'?'Sol Erda':'Erda Fragment')+' Limited · '+(!hasThird?'This class’s source order has no third skill core.':settings.includeThirdSkill?'All source skill cores included.':'Third skill core excluded. Other milestones keep their source order; this is not a recalculated GMS optimum.');
 const activeOrder=E.sourceOrder(c,settings);const rows=E.plan(c,p,settings),summary=E.summary(c,p,settings),next=rows[0];$('progress-percent').innerHTML=`${summary.percent.toFixed(1)}<span>%</span>`;$('progress-fill').style.width=summary.percent+'%';const progress=$('progress-fill').parentElement;progress.setAttribute('aria-valuenow',summary.percent.toFixed(1));progress.setAttribute('aria-valuetext',summary.percent.toFixed(1)+' percent of fragment goal');$('completed-count').textContent=`${activeOrder.filter(s=>p.levels[s.id]>=s.to).length} / ${activeOrder.length} milestones`;$('fragments-remaining').textContent=fmt(summary.remainingF);$('fragments-spent').textContent=`${fmt(summary.spentF)} of ${fmt(summary.totalF)} invested`;$('erda-remaining').textContent=fmt(summary.remainingE);$('erda-spent').textContent=`${fmt(summary.spentE)} of ${fmt(summary.totalE)} invested`;
 $('roadmap-count').textContent=rows.length;$('roadmap').innerHTML=rows.length?rows.slice(0,12).map((s,i)=>{const core=coreFor(s.id);return `<button class="roadmap-item" style="--tile-color:${window.HexaOrderView.color(core)}" data-step="${i}" aria-label="Milestone ${s.n}: ${escape(core.name)}, ${core.type==='HEXA Stat'?'complete':'level '+s.to}, ${s.f} fragments" title="${escape(core.name)} · ${fmt(s.f)} fragments"><span class="roadmap-number">${String(s.n).padStart(3,'0')}</span><img src="${core.icon}" alt="" width="29" height="29"><span class="roadmap-level">${core.type==='HEXA Stat'||s.to===core.max?'MAX':`Lv. ${s.to}`}</span></button>`;}).join(''):'<div class="empty-state">All milestones in this plan are complete.</div>';$('all-order-button').disabled=!rows.length;
 $('skills-caption').textContent=isPreview()?'Fresh-start reference levels. Switch to My progression to edit.':'Enter your current levels and set your goals.';$('reset-button').disabled=isPreview();
 document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('selected',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter));});renderSkills(p,next);renderMatrix(p,next);for(const [id,key] of [['daily-input','daily'],['weekly-input','weekly'],['stock-input','stock']]){$(id).value=p[key];$(id).disabled=isPreview();}
 $('weekly-dungeon').value=p.weeklyDungeon;$('weekly-dungeon').disabled=isPreview();$('weekly-quest').checked=p.weeklyQuest;$('weekly-quest').disabled=isPreview();$('forecast-rate').textContent=summary.rate.toFixed(1)+' fragments / day';const completion=E.completionDate(summary.days);$('forecast-date').textContent=completion?completion.toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'}):'Set a farming rate';
 $('forecast-days').innerHTML=summary.days===null?'— <small>set a farming rate</small>':`${fmt(summary.days)} <small>${summary.days===1?'day':'days'}</small>`;$('forecast-note').textContent=summary.days===0?'Your inventory covers the remaining fragments.':summary.rate===0?'Enter your daily or weekly fragment income.':`${fmt(p.daily)} daily + ${fmt(summary.weeklyTotal)} weekly fragments. Weekly rewards are averaged across 7 days; the date is an estimate. Excludes Sol Erda availability.`;imageFallbacks();}
function renderMatrix(p,next){window.HexaSkillDetails.hide();const result=window.HexaMatrix.render({c:current(),p,next,selected:matrixSelected,settings,preview:isPreview()});matrixSelected=result.selected;$('matrix-canvas').innerHTML=result.html;const core=result.core; $('enhancement-panel').innerHTML=window.HexaEnhancement.render(current(),p,next,isPreview(),history.length>0); const level=window.HexaMatrix.level(core,p),disabled=isPreview()?'disabled':'';const price=core.hunting?null:E.cost(current(),core.id,level,p.goals[core.id]);const status=core.hunting?'Hunting core · tracked separately':core.type==='HEXA Stat'?(level?'Complete':'Not complete'):level===0?'Not unlocked':'Level '+level+' / '+core.max;let controls='';if(core.hunting)controls=`<label>Current level<input id="matrix-janus-level" type="text" inputmode="numeric" pattern="[0-9]*" autocomplete="off" min="0" max="30" value="${level}" data-janus aria-label="Sol Janus matrix current level" ${disabled}></label>`;else if(core.type==='HEXA Stat')controls=`<label class="matrix-stat-label"><input type="checkbox" data-stat="${core.id}" aria-label="${escape(core.name)} matrix complete" ${level?'checked':''} ${disabled}>Milestone complete</label>`;else controls=`<label>Current level<input id="matrix-current-level" type="text" inputmode="numeric" pattern="[0-9]*" autocomplete="off" min="${core.initial}" max="${core.max}" value="${level}" data-level="${core.id}" aria-label="${escape(core.name)} matrix current level" ${disabled}></label><label>Goal<input id="matrix-goal-level" type="text" inputmode="numeric" pattern="[0-9]*" autocomplete="off" min="${level}" max="${core.max}" value="${p.goals[core.id]}" data-goal="${core.id}" aria-label="${escape(core.name)} matrix target level" ${disabled}></label>`;$('matrix-selection').innerHTML=`<div class="matrix-selection-title">${skillIcon(core)}<div><div class="core-kicker">${escape(core.type.toUpperCase())}${next?.id===core.id?' · NEXT UPGRADE':''}</div><h4 title="${escape(core.nameKo)}">${escape(core.name)}</h4><p>${escape(status)}${price?' · '+fmt(price.f)+' fragments / '+fmt(price.e)+' Sol Erda to goal':''}</p></div></div><div class="matrix-selection-controls">${controls}</div><button class="subtle-button matrix-description-button" data-description-open="${core.id}">${icon('info')}Skill description</button>${core.hunting?'<p class="matrix-selection-note">Sol Janus is saved with your class. It is not included in the damage HEXA Order or its cost totals.</p>':isPreview()?'<p class="matrix-selection-note">Switch to My progression to edit your levels.</p>':''}`;imageFallbacks();}
function renderSkills(p,next){const c=current(),types=['Mastery','Skill','Boost','Common','HEXA Stat'],head='<div class="levels-head"><span>SKILL / REMAINING COST</span><span>CURRENT</span><span></span><span>GOAL</span></div>';let html=head;for(const type of types){if(filter!=='All'&&filter!==type)continue;const cores=E.activeCores(c,settings).filter(core=>core.type===type).sort((a,b)=>a.id.localeCompare(b.id));if(!cores.length)continue;html+=`<div class="skill-group-heading"><span class="group-dot"></span>${type.toUpperCase()}${type==='HEXA Stat'?'':' CORES'} <span>· ${cores.length}</span></div><div class="group-rows">`;for(const core of cores){const cost=E.cost(c,core.id,p.levels[core.id],p.goals[core.id]),done=p.levels[core.id]>=p.goals[core.id],disabled=isPreview()?'disabled':'';html+=`<div class="skill-row ${core.id===next?.id?'next-row':''} ${type==='HEXA Stat'?'stat-row':''}" data-core-row="${core.id}">${skillIcon(core)}<div><div class="skill-name" title="${escape(core.nameKo)}">${escape(core.name)}</div><div class="skill-cost">${done?`${icon('check')} Target reached`:`<span class="gem"></span>${fmt(cost.f)}<span class="sep">/</span><span class="erda"></span>${fmt(cost.e)} to goal`}</div></div>`;if(type==='HEXA Stat'){html+=`<input class="stat-checkbox" type="checkbox" data-stat="${core.id}" aria-label="${escape(core.name)} complete" ${p.levels[core.id]>=core.max?'checked':''} ${disabled}><span class="stat-state">${p.levels[core.id]>=core.max?'Complete':'Not complete'}</span>`;}else{html+=`<div class="level-control"><button data-adjust="-1" data-core="${core.id}" aria-label="Decrease ${escape(core.name)} current level" ${disabled||p.levels[core.id]<=core.initial?'disabled':''}>−</button><input type="text" inputmode="numeric" pattern="[0-9]*" autocomplete="off" min="${core.initial}" max="${core.max}" value="${p.levels[core.id]}" id="bulk-level-${core.id}" data-level="${core.id}" aria-label="${escape(core.name)} current level" ${disabled}><button data-adjust="1" data-core="${core.id}" aria-label="Increase ${escape(core.name)} current level" ${disabled||p.levels[core.id]>=core.max?'disabled':''}>+</button></div><span class="row-arrow">${icon('arrow-right')}</span><input type="text" class="goal-input" inputmode="numeric" pattern="[0-9]*" autocomplete="off" min="${p.levels[core.id]}" max="${core.max}" value="${p.goals[core.id]}" id="bulk-goal-${core.id}" data-goal="${core.id}" aria-label="${escape(core.name)} target level" ${disabled}>`;}html+='</div>';}html+='</div>';}$('skills-list').innerHTML=html;}
function dialog(title,body,eyebrow='HEXA PLANNER',fullOrder=false){window.HexaSkillDetails.hide();window.HexaOrderView.unmount();$('dialog').classList.toggle('full-order-dialog',fullOrder);$('dialog-title').textContent=title;$('dialog-eyebrow').textContent=eyebrow;$('dialog-body').innerHTML=body;if(!$('dialog').open)$('dialog').showModal();imageFallbacks();}
function showOrder(){const c=current(),p=profile(),rows=E.plan(c,p,settings),total=rows.at(-1);dialog(`${c.name} upgrade order`,`<div class="table-summary"><span><strong>${rows.length}</strong> remaining milestones</span><span><strong>${fmt(total?.totalF||0)}</strong> fragments</span><span><strong>${fmt(total?.totalE||0)}</strong> Sol Erda</span></div>${window.HexaOrderView.markup(c,rows)}`,(settings.orderMode==='erda'?'SOL ERDA LIMITED':'ERDA FRAGMENT LIMITED')+' / '+(isPreview()?'CLASS PREVIEW':'YOUR PROGRESSION'),true);$('dialog').scrollTop=0;window.HexaOrderView.mount($('dialog'));}
function showStep(i){const p=profile(),s=E.plan(current(),p,settings)[i];if(!s)return;const core=coreFor(s.id);dialog(core.name,`<div class="milestone-detail">${skillIcon(core,true)}<div><div class="core-kicker">${escape(core.type.toUpperCase())} · SOURCE STEP ${s.n}</div><h3>${core.type==='HEXA Stat'?'Complete this HEXA Stat milestone':`Level ${s.from} → ${s.to}`}</h3><p>${escape(core.nameKo)}</p></div></div><dl class="data-facts"><div><dt>This milestone</dt><dd>${fmt(s.f)} fragments · ${fmt(s.e)} Sol Erda</dd></div><div><dt>Through this milestone</dt><dd>${fmt(s.totalF)} fragments · ${fmt(s.totalE)} Sol Erda</dd></div></dl><p class="dialog-copy">${i===0?'This is the next milestone in your current plan.':'Follow the earlier milestones first to preserve the reference upgrade order.'}</p><div class="milestone-skill-description">${window.HexaSkillDetails.markup(current(),core,s.to,{target:true})}</div><div class="dialog-actions"><button class="outline-button" data-action="full-order">View full order ${icon('arrow-right')}</button></div>`,'UPGRADE MILESTONE');}
function mark(){if(isPreview()){mode='progress';renderPlanner();toast('Tracking '+current().name+'. Your saved levels are active.');return;}const p=profile(),next=E.plan(current(),p,settings)[0];if(!next)return;capture();p.levels[next.id]=next.to;p.stock=Math.max(0,p.stock-next.f);p.erdaStock=Math.max(0,p.erdaStock-next.e);update(p);toast(`${coreFor(next.id).name} ${coreFor(next.id).type==='HEXA Stat'?'completed':'upgraded to level '+next.to}`);}
function undo(){const h=history.pop();if(!h||h.classId!==selected)return;drafts[selected]=h.profile;save();renderPlanner();toast('Last change undone.');}
function reset(){dialog('Reset '+current().name+'?',`<p class="dialog-copy">Return this class to fresh-start levels and maximum goals. Your farming settings and other class plans will stay saved.</p><div class="dialog-actions"><button class="outline-button" data-action="close">Keep my progress</button><button class="primary-button" data-action="confirm-reset">Reset this class</button></div>`);}
function changeLevel(id,value,goal=false){if(isPreview())return;const p=profile(),core=coreFor(id);if(E.clamp(value,goal?p.levels[id]:core.initial,core.max)===(goal?p.goals[id]:p.levels[id]))return;capture();if(goal)p.goals[id]=E.clamp(value,p.levels[id],core.max);else{p.levels[id]=E.clamp(value,core.initial,core.max);p.goals[id]=Math.max(p.goals[id],p.levels[id]);}update(p);}
async function importPlan(file){if(!file)return;try{if(file.size>1000000)throw Error('This file is too large to be a plan.');const data=JSON.parse(await file.text());if(data.format!=='hexa-planner'||data.version!==1)throw Error('Choose a HEXA planner export (version 1).');const c=D.classes.find(c=>c.id===data.classId&&c.available);if(!c)throw Error('This plan uses an unsupported class.');for(const core of c.cores){const l=data.levels?.[core.id],g=data.goals?.[core.id];if(!Number.isInteger(l)||!Number.isInteger(g)||l<core.initial||l>core.max||g<l||g>core.max)throw Error('The plan contains invalid skill levels.');if(core.type==='HEXA Stat'&&l!==0&&l!==core.max)throw Error('The plan contains an invalid HEXA Stat state.');}for(const k of ['daily','weekly','stock'])if(!Number.isInteger(data[k])||data[k]<0||data[k]>10000000)throw Error('The plan contains invalid farming settings.');if(data.weeklyDungeon!==undefined&&!Object.hasOwn(E.dungeonRewards,data.weeklyDungeon))throw Error('The plan contains an invalid weekly dungeon.');if(data.weeklyQuest!==undefined&&typeof data.weeklyQuest!=='boolean')throw Error('The plan contains an invalid weekly quest setting.');if(data.erdaStock!==undefined&&(!Number.isInteger(data.erdaStock)||data.erdaStock<0||data.erdaStock>20))throw Error('The plan contains an invalid Sol Erda inventory.');if(data.settings!==undefined&&(!data.settings||!['erda','fragments'].includes(data.settings.orderMode)||typeof data.settings.includeThirdSkill!=='boolean'))throw Error('The plan contains invalid order settings.');const importedSettings=data.settings?E.settings(data.settings):settings;if(data.extraLevels!==undefined&&(!data.extraLevels||!Number.isInteger(data.extraLevels.generalCore1)||data.extraLevels.generalCore1<0||data.extraLevels.generalCore1>30))throw Error('The plan contains an invalid Sol Janus level.');const imported=E.clean(c,data);dialog('Import '+c.name+'?',`<p class="dialog-copy">Replace the locally saved ${escape(c.name)} plan with this file? Your other class plans will stay saved.</p><div class="dialog-actions"><button class="outline-button" data-action="close">Cancel</button><button class="primary-button" id="confirm-import">Import plan</button></div>`);$('confirm-import').onclick=()=>{drafts[c.id]=imported;settings=importedSettings;mode='progress';$('dialog').close();chooseClass(c.id);toast('Plan imported.');};}catch(e){toast(e.message||'Could not read this plan.');}finally{$('import-file').value='';}}
function closeLibrary(){const mobile=matchMedia('(max-width:760px)').matches;if(mobile&&$('sidebar').contains(document.activeElement))$('menu-button').focus();$('sidebar').classList.remove('open');$('sidebar').inert=mobile;$('sidebar-backdrop').hidden=true;$('menu-button').setAttribute('aria-expanded','false');}
$('class-list').onclick=e=>{const b=e.target.closest('[data-class]');if(b)chooseClass(b.dataset.class);};$('class-search').oninput=e=>{query=e.target.value;renderLibrary();};$('category').onchange=e=>{category=e.target.value;renderLibrary();};
$('progress-mode').onclick=()=>{mode='progress';renderPlanner();};$('preview-mode').onclick=()=>{mode='preview';renderPlanner();};$('import-button').onclick=()=>$('import-file').click();$('import-file').onchange=e=>importPlan(e.target.files[0]);$('all-order-button').onclick=showOrder;$('reset-button').onclick=reset;$('close-dialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('dialog').close();}});
$('menu-button').onclick=()=>{$('sidebar').inert=false;$('sidebar').classList.toggle('open');const open=$('sidebar').classList.contains('open');$('sidebar-backdrop').hidden=!open;$('menu-button').setAttribute('aria-expanded',String(open));if(open)$('class-search').focus();else closeLibrary();};$('sidebar-backdrop').onclick=closeLibrary;
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLibrary();if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('dialog').open){e.preventDefault();if(innerWidth<=760){$('sidebar').inert=false;$('sidebar').classList.add('open');$('sidebar-backdrop').hidden=false;$('menu-button').setAttribute('aria-expanded','true');}$('class-search').focus();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='enhance-node-button'){mark();return;}if(b.dataset.descriptionOpen){const core=b.dataset.descriptionOpen==='generalCore1'?window.HexaMatrix.janus:coreFor(b.dataset.descriptionOpen);if(core)dialog(core.name,window.HexaSkillDetails.markup(current(),core,window.HexaMatrix.level(core,profile())),'SKILL DESCRIPTION');return;}if(b.dataset.matrixCore){matrixSelected=b.dataset.matrixCore;renderMatrix(profile(),E.plan(current(),profile(),settings)[0]);document.querySelector('[data-matrix-core="'+matrixSelected+'"]')?.focus({preventScroll:true});}if(b.dataset.orderMode){settings.orderMode=b.dataset.orderMode;save();renderPlanner();}if(b.id==='undo-button')undo();if(b.dataset.filter){filter=b.dataset.filter;renderPlanner();}if(b.dataset.adjust){const p=profile();changeLevel(b.dataset.core,p.levels[b.dataset.core]+Number(b.dataset.adjust));}if(b.dataset.step!==undefined)showStep(+b.dataset.step);if(b.dataset.action==='full-order')showOrder();if(b.dataset.action==='close')$('dialog').close();if(b.dataset.action==='choose-available')chooseClass('night_lord');if(b.dataset.action==='confirm-reset'){capture();const p=profile(),d=E.defaults(current());update({...d,daily:p.daily,weekly:p.weekly,weeklyDungeon:p.weeklyDungeon,weeklyQuest:p.weeklyQuest,stock:p.stock,erdaStock:p.erdaStock});$('dialog').close();toast('Class reset. Use undo to restore it.');}if(b.dataset.action==='max-goals'){if(isPreview()){mode='progress';renderPlanner();return;}capture();const p=profile();for(const core of current().cores)p.goals[core.id]=core.max;update(p);toast('All targets set to maximum.');}});
let inputTimer;
document.addEventListener('focusin',e=>{if(levelField(e.target)&&!restoringLevelFocus)e.target.select();});
document.addEventListener('keydown',e=>{if(levelField(e.target)&&e.key==='Enter'){e.preventDefault();e.target.blur();}});
document.addEventListener('focusout',e=>{const el=e.target;if(levelField(el)&&el.isConnected){el.value=String(E.clamp(el.value,Number(el.min),Number(el.max)));el.dispatchEvent(new Event('change',{bubbles:true}));}});
document.addEventListener('input',e=>{
 const el=e.target;
 if(levelField(el)){
  clearTimeout(inputTimer);
  const caret=el.selectionStart,raw=el.value,digits=raw.replace(/[^0-9]/g,'').replace(/^0+(?=\d)/,'');
  const value=digits===''?'':String(Math.min(Number(digits),Number(el.max)));
  if(value!==raw){el.value=value;const position=Math.max(0,caret-(raw.length-value.length));el.setSelectionRange(position,position);}
  if(value!=='')el.dispatchEvent(new Event('change',{bubbles:true}));
  return;
 }
 if(!['daily-input','weekly-input','stock-input'].includes(el.id))return;
 clearTimeout(inputTimer);if(el.value==='')return;
 const classAtInput=selected,modeAtInput=mode;
 inputTimer=setTimeout(()=>{if(selected!==classAtInput||mode!==modeAtInput)return;const focused=document.activeElement===el;el.dispatchEvent(new Event('change',{bubbles:true}));if(focused)$(el.id)?.focus();},350);
});
document.addEventListener('change',e=>{clearTimeout(inputTimer);const el=e.target;if(['weekly-dungeon','weekly-quest'].includes(el.id)&&!isPreview()){const p=profile();capture();if(el.id==='weekly-dungeon')p.weeklyDungeon=el.value;else p.weeklyQuest=el.checked;update(p);return;}if(el.dataset.material&&!isPreview()){const p=profile(),key=el.dataset.material,value=E.clamp(el.value,0,key==='erdaStock'?20:10000000);if(p[key]!==value){capture();p[key]=value;update(p);}return;}if(el.hasAttribute('data-janus')&&!isPreview()){const p=profile(),value=E.clamp(el.value,0,30);if(value!==p.extraLevels.generalCore1){capture();p.extraLevels.generalCore1=value;update(p);}}if(el.id==='include-third'){settings.includeThirdSkill=el.checked;save();renderPlanner();}if(el.dataset.level)changeLevel(el.dataset.level,el.value);if(el.dataset.goal)changeLevel(el.dataset.goal,el.value,true);if(el.dataset.stat){const p=profile(),core=coreFor(el.dataset.stat);capture();p.levels[core.id]=el.checked?core.max:0;update(p);}const keys={'daily-input':'daily','weekly-input':'weekly','stock-input':'stock'};if(keys[el.id]&&!isPreview()){const p=profile();capture();p[keys[el.id]]=E.clamp(el.value,0,10000000);update(p);}});
window.HexaSkillDetails.mount(el=>{let id=el.dataset.describe||el.dataset.matrixCore,target=false,level;if(el.dataset.step!==undefined){const row=E.plan(current(),profile(),settings)[+el.dataset.step];if(!row)return;id=row.id;level=row.to;target=true;}const core=id==='generalCore1'?window.HexaMatrix.janus:coreFor(id);return core?{c:current(),core,level:level??window.HexaMatrix.level(core,profile()),target}:null;});
renderLibrary();renderPlanner();
$('class-list').querySelector('.selected')?.scrollIntoView({block:'center'});
closeLibrary();
matchMedia('(max-width:760px)').addEventListener('change',closeLibrary);
})();



