(function ui(root){
 'use strict';
 const S=root.HexaStats,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const percent=n=>Number.isFinite(n)?'+'+n.toFixed(2)+'%':'—';
 function gain(c,row,options){const type=options?.bossMode==='kaling'&&c.kalingOrders?.[options?.orderMode||'fragments']?'kaling':'general',mode=options?.orderMode==='erda'?'erda':'fragments',data=root.HEXA_DAMAGE?.classes?.[c.id]?.orders?.[type+'_'+mode];if(!data)return null;return data.find(r=>r.id===row.id&&r.from===row.from&&r.to===row.to)?.fd??null;}
 function detail(c,row,options){if(row.to!==row.from+1||row.id.startsWith('hexaStat'))return '';return root.HexaLevelDamage.markup(c,row,options);}

 function render(c,p,options,preview){
 const state=S.clean(p.hexaStats),r=S.result(c,state),disabled=preview?'disabled':'',eff=S.effective(c,state);
 return `<div class="section-heading"><div><div class="section-kicker">DAMAGE & STAT PLANNING</div><h3>HEXA Stats</h3><p>Enter the levels of your three lines, then compare stat assignments.</p></div><span class="damage-badge">${state.basis==='custom'?'CUSTOM ESTIMATE':'REFERENCE ESTIMATE'}</span></div>
 <p class="damage-explainer">FD means final damage. Choose this class’s available reference or supply your own stat efficiencies, with 100% critical rate assumed. They are not your character’s exact gain and do not change the skill upgrade order.</p>
 <details class="damage-method custom-efficiencies" ${state.basis==='custom'?'open':''}><summary>Use my own stat efficiencies</summary><label class="custom-basis"><input id="hexa-custom-basis" type="checkbox" ${state.basis==='custom'?'checked':''} ${disabled}> Use custom efficiencies instead of the class reference</label><p>Enter FD percentages measured for the stated increase, before the HEXA Stats entered here. Use your calculator’s buffed bossing setup at 380% PDR and 100% critical rate. Boss Damage and Damage share the same efficiency. Zero means no benefit.</p><div class="custom-eff-grid">${[['attack','+1 ATT / Magic ATT'],['main',c.id==='demon_avenger'?'+100 flat HP':c.id==='xenon'?'+100 flat All Stats':'+100 flat Main Stat'],['boss','+1% Boss Damage / Damage'],['critical','+1% Critical Damage'],['ied','One extra 1% IED line']].map(([key,name])=>`<label>${name}<span><input id="hexa-eff-${key}" data-hexa-eff="${key}" aria-label="FD percent for ${name}" type="number" step="any" min="0" max="100" value="${state.custom[key]}" ${disabled||state.basis!=='custom'?'disabled':''}> % FD</span></label>`).join('')}</div></details>
 <p class="stat-basis-note">Using: <strong>${state.basis==='custom'?'your supplied efficiencies':c.name+' reference profile'}</strong></p><div class="stat-nodes">${state.nodes.map((n,i)=>`<fieldset class="stat-node${n.enabled?'':' inactive'}"><legend><label><input type="checkbox" data-hexa-enabled="${i}" ${n.enabled?'checked':''} ${disabled}> Node ${['I','II','III'][i]}</label><span>${n.levels.reduce((a,b)=>a+b,0)} / 20</span></legend>${n.stats.map((key,j)=>`<div class="stat-line"><label for="hexa-choice-${i}-${j}">${j===0?'Main line':'Additional '+j}</label><select id="hexa-choice-${i}-${j}" aria-label="Node ${i+1} ${j===0?'main':'additional '+j} stat" data-hexa-choice="${i}:${j}" ${disabled||!n.enabled?'disabled':''}>${S.keys.map(k=>`<option value="${k}" ${k===key?'selected':''}>${esc(S.label(c,k))}</option>`).join('')}</select><label class="stat-roll-label" for="hexa-roll-${i}-${j}">Level<input id="hexa-roll-${i}-${j}" type="text" inputmode="numeric" autocomplete="off" min="0" max="10" value="${n.levels[j]}" data-hexa-roll="${i}:${j}" aria-label="Node ${i+1} ${j===0?'main':'additional '+j} line level" ${disabled||!n.enabled?'disabled':''}></label><span class="stat-line-value">+${S.amount(c,key,n.levels[j],j===0).toLocaleString('en-US',{maximumFractionDigits:2})}${['attack','main'].includes(key)?'':'%'}</span></div>`).join('')}</fieldset>`).join('')}</div>
 <div class="stat-results"><div><span>Estimated FD from these stats</span><strong>${percent(r.fd)}</strong><small>Compared with the selected baseline before these HEXA Stats.</small></div><div><button class="primary-button" id="compare-hexa-stats" ${disabled||!eff||state.nodes.some(n=>n.enabled&&n.levels.reduce((a,b)=>a+b,0)>20)||!state.nodes.some(n=>n.enabled)?'disabled':''}>Find best stat assignment</button><small>Keeps your rolls. Checks valid assignments across all active nodes.</small></div></div>
 <div class="stat-validation" role="status">${r.errors.map(e=>`<p>${esc(e)}</p>`).join('')}${!eff?'<p>No usable efficiencies for this selection. Use your own efficiencies above; stat amounts still work.</p>':''}</div>
 <div id="stat-recommendation" aria-live="polite"></div>
 <details class="damage-method"><summary>How these estimates work</summary><p>Main lines scale faster at higher rolls; additional lines scale evenly. Each line caps at 10 and each node at 20. Main stats cannot repeat across nodes; each additional stat can appear twice. Disabled nodes are excluded.</p><p>FD combines the class’s reference stat efficiencies, adding shared damage bonuses and stacking separate IED lines multiplicatively. Recommendations compare assignments for your existing rolls, not the cost or chance of rerolling. This is a marginal-stat model, not a simulation of your rotation, gear or buffs.</p><p>HEXA Stat completion checkboxes in the matrix are separate. Editing rolls here does not spend materials or mark milestones complete.</p><p><a href="https://maplescouter.com/en/hexa" target="_blank" rel="noopener noreferrer">MapleScouter reference calculator</a> · <a href="https://www.maplesea.com/newage/6th/" target="_blank" rel="noopener noreferrer">Official HEXA Stat overview</a> · <a href="https://maplestorywiki.net/w/6th_Job#HEXA_Stats" target="_blank" rel="noopener noreferrer">Stat level tables</a></p></details>`;
 }
 function recommendation(c,p){const r=S.recommend(c,p.hexaStats),before=S.result(c,p.hexaStats);if(!r)return null;
 const improvement=before.fd===null?null:((1+r.fd/100)/(1+before.fd/100)-1)*100;
 return {state:r.state,html:`<div class="stat-recommendation"><h4>Best assignment for these rolls</h4><p><strong>${percent(r.fd)} estimated total FD</strong>${improvement===null?'':` · ${improvement<.005?'Your assignment is already tied for best.':percent(improvement)+' versus your current assignment.'}`}</p><div>${r.state.nodes.map((n,i)=>n.enabled?`<p><b>Node ${['I','II','III'][i]}</b> <span>Main: ${esc(S.label(c,n.stats[0]))} (${n.levels[0]}) · ${esc(S.label(c,n.stats[1]))} (${n.levels[1]}) · ${esc(S.label(c,n.stats[2]))} (${n.levels[2]})</span></p>`:'').join('')}</div><button class="outline-button" id="apply-hexa-stats">Use this assignment in planner</button><small>This updates the planner only. Changing assigned stats in-game costs mesos.</small></div>`};
 }
 root.HexaDamageUI={render,recommendation,gain,detail,percent};
})(window);
