(function(root){
 'use strict';
 const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Math.floor(Number(v)):min));
 const dungeonRewards={none:0,high_mountain:40,angler_company:55,nightmare_paradise:70};
 function defaults(c){return {levels:Object.fromEntries(c.cores.map(x=>[x.id,x.initial])),goals:Object.fromEntries(c.cores.map(x=>[x.id,x.max])),daily:100,weekly:0,weeklyDungeon:'none',weeklyQuest:false,stock:0,erdaStock:0,extraLevels:{generalCore1:0}};}
 function clean(c,p={}){const d=defaults(c);for(const core of c.cores){d.levels[core.id]=clamp(p.levels?.[core.id]??core.initial,core.initial,core.max);d.goals[core.id]=clamp(p.goals?.[core.id]??core.max,d.levels[core.id],core.max);}d.extraLevels.generalCore1=clamp(p.extraLevels?.generalCore1??0,0,30);d.erdaStock=clamp(p.erdaStock??0,0,20);d.weeklyDungeon=Object.hasOwn(dungeonRewards,p.weeklyDungeon)?p.weeklyDungeon:'none';d.weeklyQuest=p.weeklyQuest===true;for(const key of ['daily','weekly','stock'])d[key]=clamp(p[key]??d[key],0,10000000);return d;}
 function enhancement(c,p,id){const core=c.cores.find(x=>x.id===id),level=p.levels[id];if(!core||core.type==='HEXA Stat')return {available:false,reason:'Upgrade costs are not available for this node.'};if(level>=core.max)return {available:false,maxed:true,reason:'This node is at maximum level.'};if(!c.costs?.[id])return {available:false,reason:'Upgrade costs are not available for this node.'};const price=cost(c,id,level,level+1);return {available:true,from:level,to:level+1,...price,affordable:p.stock>=price.f&&p.erdaStock>=price.e};}
 function enhance(c,p,id){const state=enhancement(c,p,id);if(!state.available||!state.affordable)return null;const updated=clean(c,p);updated.levels[id]=state.to;updated.goals[id]=Math.max(updated.goals[id],state.to);updated.stock-=state.f;updated.erdaStock-=state.e;return updated;}
 function cost(c,id,from,to){if(to<=from)return {f:0,e:0};const table=c.costs[id];if(table)return {f:table.f[to]-table.f[from],e:table.e[to]-table.e[from]};const row=c.order.find(s=>s.id===id);return row?{f:row.f,e:row.e}:{f:0,e:0};}
 function settings(value={}){return {orderMode:value?.orderMode==='erda'?'erda':'fragments',includeThirdSkill:value?.includeThirdSkill===true};}
 function activeCores(c,options){const s=settings(options);return c.cores.filter(core=>s.includeThirdSkill||core.id!=='skillCore3');}
 function sourceOrder(c,options){const s=settings(options),order=c.orders?.[s.orderMode]||(s.orderMode==='fragments'?c.order:[]);return order.filter(step=>s.includeThirdSkill||step.id!=='skillCore3');}
 function plan(c,p,options){const levels={...p.levels},rows=[];let totalF=0,totalE=0;for(const step of sourceOrder(c,options)){const target=Math.min(step.to,p.goals[step.id]);if(target<=levels[step.id])continue;const from=levels[step.id],price=cost(c,step.id,from,target);totalF+=price.f;totalE+=price.e;rows.push({...step,from,to:target,f:price.f,e:price.e,totalF,totalE});levels[step.id]=target;}return rows;}
 function completionDate(days,start=new Date()){if(days===null||!Number.isFinite(days)||days<0)return null;const date=new Date(start);date.setHours(12,0,0,0);date.setDate(date.getDate()+Math.ceil(days));return Number.isFinite(date.getTime())?date:null;}
 function summary(c,p,options){let spentF=0,totalF=0,spentE=0,totalE=0;for(const core of activeCores(c,options)){const full=cost(c,core.id,core.initial,p.goals[core.id]),spent=cost(c,core.id,core.initial,p.levels[core.id]);totalF+=full.f;totalE+=full.e;spentF+=spent.f;spentE+=spent.e;}const remainingF=totalF-spentF,remainingE=totalE-spentE,weeklyTotal=p.weekly+(dungeonRewards[p.weeklyDungeon]||0)+(p.weeklyQuest?90:0),rate=p.daily+weeklyTotal/7,needed=Math.max(0,remainingF-p.stock);return {spentF,spentE,totalF,totalE,remainingF,remainingE,percent:totalF?100*spentF/totalF:100,rate,weeklyTotal,needed,days:needed===0?0:rate>0?Math.ceil(needed/rate):null};}
 const api={clamp,defaults,clean,cost,settings,activeCores,sourceOrder,plan,summary,enhancement,enhance,dungeonRewards,completionDate};if(typeof module!=='undefined')module.exports=api;else root.HexaEngine=api;
})(typeof window!=='undefined'?window:globalThis);
