(function(root){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const material=(kind)=>`<span class="material-orb material-${kind}" aria-hidden="true"><img src="assets/${kind==='erda'?'sol-erda':'sol-erda-fragment'}.png" alt="" width="48" height="48"></span>`;
 function render(c,p,core,preview){
  const E=root.HexaEngine,s=E.enhancement(c,p,core.id),level=core.hunting?p.extraLevels.generalCore1:p.levels[core.id],hasNext=core.type!=='HEXA Stat'&&level<core.max,next=hasNext?level+1:level;
  const missing=s.available?[p.erdaStock<s.e?`${s.e-p.erdaStock} Sol Erda`:'',p.stock<s.f?`${s.f-p.stock} fragments`:''].filter(Boolean):[];
  return `<section class="enhancement-panel" aria-label="Selected node enhancement"><div class="material-owned"><h3>Material Owned</h3><div class="material-inventory"><label>${material('erda')}<span>Sol Erda</span><div><input id="owned-erda" type="text" inputmode="numeric" autocomplete="off" min="0" max="20" value="${p.erdaStock}" data-material="erdaStock" aria-label="Sol Erda owned" ${preview?'disabled':''}><small>/ 20</small></div></label><label>${material('fragment')}<span>Erda Fragments</span><input id="owned-fragments" type="text" inputmode="numeric" autocomplete="off" min="0" max="10000000" value="${p.stock}" data-material="stock" aria-label="Erda Fragments owned" ${preview?'disabled':''}></label></div></div><div class="enhance-node"><h3>Enhance Node</h3><div class="enhance-description" tabindex="0" role="region" aria-label="${esc(core.name)} ${hasNext?'next level':'skill'} description"><span class="enhance-type">${esc(core.type)} Node</span>${root.HexaSkillDetails.markup(c,core,next,{target:hasNext?'next':false})}</div><div class="enhance-cost" aria-label="Next level upgrade cost">${s.available?`<div>${material('erda')}<span>Sol Erda</span><strong class="${p.erdaStock<s.e?'material-short':''}">${s.e.toLocaleString('en-US')}</strong></div><b aria-hidden="true">+</b><div>${material('fragment')}<span>Fragments</span><strong class="${p.stock<s.f?'material-short':''}">${s.f.toLocaleString('en-US')}</strong></div>`:`<p>${esc(s.reason)}</p>`}</div><button id="enhance-node-button" class="enhance-button" ${preview||!s.available||!s.affordable?'disabled':''}>${s.maxed?'Max level':level===0?'Unlock':'Enhance'}${s.available?` <span>Lv. ${s.from} → ${s.to}</span>`:''}</button><p class="enhance-status">${preview?'Switch to My progression to edit materials and enhance.':missing.length?'Need '+missing.join(' and ')+'.':s.available?'Uses your saved materials for one level.':core.hunting?'Sol Janus levels can still be edited in the matrix.':'Select another node to enhance.'}</p></div></section>`;
 }
 root.HexaEnhancement={render};
})(window);
