(function(root){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const material=kind=>`<span class="material-orb material-${kind}" aria-hidden="true"><img src="assets/${kind==='erda'?'sol-erda':'sol-erda-fragment'}.png" alt="" width="48" height="48"></span>`;
 function render(c,p,next,preview,canUndo=false){
  const core=next&&c.cores.find(core=>core.id===next.id);
  const undo=`<button id="undo-button" class="subtle-button enhance-undo" aria-label="Undo last change" ${canUndo&&!preview?'':'disabled'}>↶ Undo</button>`;
  const inventory=`<div class="material-owned"><h3>Material Owned</h3><div class="material-inventory"><label>${material('erda')}<span>Sol Erda</span><div><input id="owned-erda" type="text" inputmode="numeric" autocomplete="off" min="0" max="20" value="${p.erdaStock}" data-material="erdaStock" aria-label="Sol Erda owned" ${preview?'disabled':''}><small>/ 20</small></div></label><label>${material('fragment')}<span>Erda Fragments</span><input id="owned-fragments" type="text" inputmode="numeric" autocomplete="off" min="0" max="10000000" value="${p.stock}" data-material="stock" aria-label="Erda Fragments owned" ${preview?'disabled':''}></label></div></div>`;
  const content=core?`<p class="enhance-order-step">HEXA ORDER · STEP ${String(next.n).padStart(3,'0')}</p><div class="enhance-description" tabindex="0" role="region" aria-label="${esc(core.name)} next upgrade description"><span class="enhance-type">${esc(core.type)}${core.type==='HEXA Stat'?'':' Node'}</span>${root.HexaSkillDetails.markup(c,core,next.to,{target:'next'})}</div><div class="enhance-cost" aria-label="Cost for this enhancement"><div>${material('erda')}<span>Sol Erda</span><strong>${next.e.toLocaleString('en-US')}</strong></div><b aria-hidden="true">+</b><div>${material('fragment')}<span>Fragments</span><strong>${next.f.toLocaleString('en-US')}</strong></div></div><button id="enhance-node-button" class="enhance-button">${preview?'Start tracking this class':'Enhance'}<span>${core.type==='HEXA Stat'?'Complete HEXA Stat':`Lv. ${next.from} → ${next.to}`}</span></button><p class="enhance-status">${preview?'Fresh-start reference. Your saved levels are unchanged.':core.type==='HEXA Stat'?'Marks this HEXA Stat milestone complete. Owned materials are optional.':'Enhances one level in HEXA Order. Owned materials are optional.'}</p>${undo}`:`<div class="enhance-complete"><h4>Goal reached.</h4><p>All selected HEXA Order milestones are complete.</p><button class="outline-button" data-action="max-goals">Set all goals to maximum</button>${undo}</div>`;
  return `<section class="enhancement-panel" aria-label="Next recommended enhancement">${inventory}<div class="enhance-node"><h3>Enhance Node</h3>${content}</div></section>`;
 }
 root.HexaEnhancement={render};
})(window);
